---
extends: default

rules:
  line-length:
    max: 100
    allow-non-breakable-words: true
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
  document-start:
    present: true

ignore: |
  .venv/
  .molecule/
