"""Regenerate the diagrams and terminal captures used in the documentation.

Every image in `docs/assets/` is produced by this script and by nothing else. Two
consequences follow, and both are the point:

* An asset cannot drift from what it illustrates. `--check` regenerates everything
  into memory and compares it byte for byte with what is committed, so a diagram that
  no longer matches the architecture fails the build the same way a stale test does.
* A terminal capture is real output. Captures are produced by running the command and
  keeping what it printed. Nothing here draws a screenshot of behaviour that does not
  exist yet; a verb that is not built renders as a verb that is not built.

Output is deterministic: no timestamps, no random ids, no locale-dependent formatting.
Themes are rendered as separate light and dark files so the documentation can pick one
with `<picture>` rather than shipping an image that is unreadable on half the screens
that open it.

Usage:

    python tools/render_assets.py            # write docs/assets/
    python tools/render_assets.py --check    # fail if the committed assets are stale
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "docs" / "assets"

MONO = "ui-monospace, SFMono-Regular, Menlo, Consolas, 'Liberation Mono', monospace"
SANS = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif"

#: Monospace advance width as a fraction of the font size. Close enough for every
#: font in the stack above, and only used to size the canvas.
CHAR_WIDTH = 0.6

GENERATED_BY = "<!-- Generated by tools/render_assets.py. Do not edit by hand. -->"


@dataclass(frozen=True)
class Theme:
    """The colours of one rendering. Values follow the palette GitHub renders with."""

    name: str
    bg: str
    panel: str
    fg: str
    muted: str
    line: str
    accent: str
    ok: str
    warn: str
    block: str


THEMES: tuple[Theme, ...] = (
    Theme(
        name="light",
        bg="#ffffff",
        panel="#f6f8fa",
        fg="#1f2328",
        muted="#59636e",
        line="#d1d9e0",
        accent="#0969da",
        ok="#1a7f37",
        warn="#9a6700",
        block="#cf222e",
    ),
    Theme(
        name="dark",
        bg="#0d1117",
        panel="#151b23",
        fg="#e6edf3",
        muted="#9198a1",
        line="#3d444d",
        accent="#4493f8",
        ok="#3fb950",
        warn="#d29922",
        block="#f85149",
    ),
)


# --------------------------------------------------------------------------- svg


def escape(text: str) -> str:
    return (
        text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
    )


def svg(width: int, height: int, body: Iterable[str]) -> str:
    """Wrap rendered elements in a document, with the arrowhead every diagram uses."""
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" role="img">',
        GENERATED_BY,
        "<defs>",
        '<marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" '
        'markerHeight="6" orient="auto">',
        '<path d="M 0 0 L 10 5 L 0 10 z" fill="context-stroke"/>',
        "</marker>",
        "</defs>",
        *body,
        "</svg>",
    ]
    return "\n".join(parts) + "\n"


def rect(
    x: float,
    y: float,
    w: float,
    h: float,
    *,
    fill: str,
    stroke: str = "none",
    radius: float = 6,
    width: float = 1,
    dash: str | None = None,
) -> str:
    dash_attr = f' stroke-dasharray="{dash}"' if dash else ""
    return (
        f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{radius}" fill="{fill}" '
        f'stroke="{stroke}" stroke-width="{width}"{dash_attr}/>'
    )


def text(
    x: float,
    y: float,
    content: str,
    *,
    fill: str,
    size: float = 13,
    family: str = SANS,
    weight: str = "normal",
    anchor: str = "start",
    spacing: str = "normal",
) -> str:
    return (
        f'<text x="{x}" y="{y}" fill="{fill}" font-family="{family}" font-size="{size}" '
        f'font-weight="{weight}" text-anchor="{anchor}" letter-spacing="{spacing}" '
        f'xml:space="preserve">{escape(content)}</text>'
    )


def line(x1: float, y1: float, x2: float, y2: float, *, stroke: str, arrow: bool = False) -> str:
    marker = ' marker-end="url(#arrow)"' if arrow else ""
    return (
        f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{stroke}" '
        f'stroke-width="1.5"{marker}/>'
    )


# ---------------------------------------------------------------- terminal cards

#: Highlighting rules applied to captured output, in order. The first match on a line
#: wins. These describe the report vocabulary, not any one engine.
HIGHLIGHTS: tuple[tuple[re.Pattern[str], str], ...] = (
    (re.compile(r"^\s*\$ "), "accent"),
    (re.compile(r"\bBLOCK\b|\bREFUSED\b|\bFAIL(ED)?\b"), "block"),
    (re.compile(r"\bWARN(ING)?\b|^\s*~ "), "warn"),
    (re.compile(r"\bPASS\b|\bOK\b|^\s*\+ "), "ok"),
    (re.compile(r"^[A-Z][A-Z ]{2,}$"), "accent"),
    (re.compile(r"^\s*#"), "muted"),
)


def _colour_for(line_text: str, theme: Theme) -> str:
    for pattern, attribute in HIGHLIGHTS:
        if pattern.search(line_text):
            return str(getattr(theme, attribute))
    return theme.fg


def render_terminal(title: str, lines: Sequence[str], theme: Theme) -> str:
    """Draw captured console output as a terminal window."""
    size = 12.5
    leading = 18
    pad = 18
    chrome = 34

    columns = max((len(line_text) for line_text in lines), default=0)
    width = int(pad * 2 + max(columns, len(title) + 12) * size * CHAR_WIDTH) + 8
    height = int(chrome + pad + max(len(lines), 1) * leading + pad)

    body: list[str] = [
        rect(0, 0, width, height, fill=theme.panel, stroke=theme.line, radius=8),
        rect(0, 0, width, chrome, fill=theme.bg, stroke="none", radius=8),
        f'<rect x="0" y="{chrome - 8}" width="{width}" height="8" fill="{theme.bg}"/>',
        line(0, chrome, width, chrome, stroke=theme.line),
    ]
    for index, colour in enumerate((theme.block, theme.warn, theme.ok)):
        body.append(f'<circle cx="{18 + index * 16}" cy="{chrome / 2}" r="5" fill="{colour}"/>')
    body.append(
        text(
            width / 2,
            chrome / 2 + 4,
            title,
            fill=theme.muted,
            size=12,
            family=SANS,
            anchor="middle",
        )
    )

    baseline = chrome + pad + leading - 5
    for index, line_text in enumerate(lines):
        body.append(
            text(
                pad,
                baseline + index * leading,
                line_text,
                fill=_colour_for(line_text, theme),
                size=size,
                family=MONO,
            )
        )
    return svg(width, height, body)


# --------------------------------------------------------------------- diagrams


def render_pipeline(theme: Theme) -> str:
    """The five verbs, and the fact that only one of them writes to the host."""
    steps = (
        ("gather", "facts"),
        ("preflight", "gates"),
        ("plan", "artifact"),
        ("apply", "change"),
        ("verify", "proof"),
    )
    box_w, box_h, gap, left, top = 158.0, 60.0, 34.0, 24.0, 46.0
    width = int(left * 2 + len(steps) * box_w + (len(steps) - 1) * gap)
    height = 196

    body: list[str] = [
        rect(0, 0, width, height, fill=theme.bg),
        text(
            left, 28, "The five verbs, always in this order", fill=theme.fg, size=14, weight="600"
        ),
    ]

    for index, (verb, subtitle) in enumerate(steps):
        x = left + index * (box_w + gap)
        writes = verb == "apply"
        border = theme.warn if writes else theme.line
        body.extend(
            (
                rect(
                    x,
                    top,
                    box_w,
                    box_h,
                    fill=theme.panel,
                    stroke=border,
                    width=2 if writes else 1,
                ),
                text(
                    x + box_w / 2,
                    top + 26,
                    verb,
                    fill=theme.fg,
                    size=16,
                    family=MONO,
                    weight="600",
                    anchor="middle",
                ),
                text(
                    x + box_w / 2,
                    top + 46,
                    subtitle,
                    fill=theme.muted,
                    size=12,
                    anchor="middle",
                ),
                text(
                    x + box_w / 2,
                    top + box_h + 26,
                    "changes the target" if writes else "reads only",
                    fill=theme.warn if writes else theme.muted,
                    size=11.5,
                    anchor="middle",
                ),
            )
        )
        if index < len(steps) - 1:
            body.append(
                line(
                    x + box_w + 8,
                    top + box_h / 2,
                    x + box_w + gap - 8,
                    top + box_h / 2,
                    stroke=theme.muted,
                    arrow=True,
                )
            )

    body.append(
        text(
            left,
            height - 22,
            "A block produces no plan, only a refusal. Warnings must be acknowledged before "
            "apply will run.",
            fill=theme.muted,
            size=12.5,
        )
    )
    return svg(width, height, body)


def render_decides_acts(theme: Theme) -> str:
    """Where the decisions are made, and where they are carried out."""
    width, height = 980, 300
    panel_w, panel_h, top = 290.0, 176.0, 62.0
    left_x, right_x = 24.0, 666.0
    middle_x, middle_w = 380.0, 220.0

    decisions = (
        "normalize host facts",
        "evaluate the gate rules",
        "size parameters from rules",
        "resolve the layout",
        "assemble and render the plan",
    )
    actions = (
        "add the vendor repository",
        "install the packages",
        "create accounts and paths",
        "write the configuration",
        "enable and start the service",
    )

    def panel(x: float, title: str, subtitle: str, items: Sequence[str], accent: str) -> list[str]:
        parts = [
            rect(x, top, panel_w, panel_h, fill=theme.panel, stroke=theme.line),
            f'<rect x="{x}" y="{top}" width="4" height="{panel_h}" rx="2" fill="{accent}"/>',
            text(x + 20, top + 30, title, fill=theme.fg, size=15, weight="600"),
            text(x + 20, top + 50, subtitle, fill=theme.muted, size=12),
        ]
        for index, item in enumerate(items):
            parts.append(
                text(x + 20, top + 78 + index * 20, f"·  {item}", fill=theme.fg, size=12.5)
            )
        return parts

    body: list[str] = [
        rect(0, 0, width, height, fill=theme.bg),
        text(
            left_x,
            34,
            "Ansible decides nothing. Python decides everything.",
            fill=theme.fg,
            size=15,
            weight="600",
        ),
        *panel(
            left_x, "Python decides", "unit-testable, no host required", decisions, theme.accent
        ),
        *panel(right_x, "Ansible acts", "idempotent, changes the host", actions, theme.warn),
        rect(
            middle_x,
            top + 52,
            middle_w,
            72,
            fill=theme.bg,
            stroke=theme.accent,
            dash="5 4",
        ),
        text(
            middle_x + middle_w / 2,
            top + 80,
            "plan.json",
            fill=theme.accent,
            size=15,
            family=MONO,
            weight="600",
            anchor="middle",
        ),
        text(
            middle_x + middle_w / 2,
            top + 102,
            "the only thing apply reads",
            fill=theme.muted,
            size=11.5,
            anchor="middle",
        ),
        line(
            left_x + panel_w + 12,
            top + 88,
            middle_x - 12,
            top + 88,
            stroke=theme.muted,
            arrow=True,
        ),
        line(
            middle_x + middle_w + 12,
            top + 88,
            right_x - 12,
            top + 88,
            stroke=theme.muted,
            arrow=True,
        ),
        text(
            left_x,
            height - 22,
            "Sizing arithmetic and gate evaluation in a template would be untestable. "
            "They live in Python, and the plan carries the result.",
            fill=theme.muted,
            size=12.5,
        ),
    ]
    return svg(width, height, body)


def render_finished_vs_fit(theme: Theme) -> str:
    """The thesis, as two columns."""
    width, height = 900, 296
    panel_w, panel_h, top = 414.0, 194.0, 58.0
    left_x, right_x = 24.0, 462.0

    finished = (
        "the job exited zero",
        "the package is present",
        "parameters are whatever the package shipped",
        "nobody checked whether the machine fits",
        "no record of a single decision",
    )
    fit = (
        "the host was gated against the requirements",
        "parameters were sized from the real facts",
        "every value carries the rule that produced it",
        "the running instance was verified against the plan",
        "the fortieth server is built like the first",
    )

    def panel(x: float, title: str, items: Sequence[str], accent: str) -> list[str]:
        parts = [
            rect(x, top, panel_w, panel_h, fill=theme.panel, stroke=theme.line),
            f'<rect x="{x}" y="{top}" width="4" height="{panel_h}" rx="2" fill="{accent}"/>',
            text(x + 20, top + 32, title, fill=accent, size=15, weight="600"),
        ]
        for index, item in enumerate(items):
            parts.append(
                text(x + 20, top + 62 + index * 24, f"·  {item}", fill=theme.fg, size=12.5)
            )
        return parts

    body: list[str] = [
        rect(0, 0, width, height, fill=theme.bg),
        text(
            left_x,
            32,
            "An install that finished is not the same thing as an instance fit for production.",
            fill=theme.fg,
            size=15,
            weight="600",
        ),
        *panel(left_x, "An install that finished", finished, theme.block),
        *panel(right_x, "An instance fit for production", fit, theme.ok),
        text(
            left_x,
            height - 20,
            "Basewright refuses to conflate the two: a host that fails preflight is refused "
            "with a reason, never half-installed.",
            fill=theme.muted,
            size=12.5,
        ),
    ]
    return svg(width, height, body)


# ------------------------------------------------------------------- collection


def capture(command: Sequence[str]) -> list[str]:
    """Run a command and keep what it printed, prompt line included."""
    result = subprocess.run(
        [sys.executable, "-m", *command],
        capture_output=True,
        text=True,
        cwd=ROOT,
        check=False,
    )
    printed = (result.stdout + result.stderr).replace("\r\n", "\n").rstrip("\n")
    shown = " ".join(command[1:]) if command[0] == "basewright.cli" else " ".join(command)
    lines = [f"$ basewright {shown}"]
    lines.extend(printed.split("\n") if printed else [])
    return [line_text.rstrip() for line_text in lines]


def build() -> dict[Path, str]:
    """Render every asset. Keys are paths relative to the repository root."""
    assets: dict[Path, str] = {}

    captures: dict[str, tuple[str, list[str]]] = {
        "cli-help": ("basewright --help", capture(["basewright.cli", "--help"])),
        "cli-plan": ("basewright plan", capture(["basewright.cli", "plan"])),
    }

    for theme in THEMES:
        suffix = theme.name
        assets[ASSETS / f"pipeline-{suffix}.svg"] = render_pipeline(theme)
        assets[ASSETS / f"decides-acts-{suffix}.svg"] = render_decides_acts(theme)
        assets[ASSETS / f"finished-vs-fit-{suffix}.svg"] = render_finished_vs_fit(theme)
        for name, (title, lines) in captures.items():
            assets[ASSETS / f"{name}-{suffix}.svg"] = render_terminal(title, lines, theme)

    return assets


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="render_assets",
        description="Regenerate the documentation diagrams and terminal captures.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; fail if what is committed differs from what would be produced.",
    )
    args = parser.parse_args(argv)

    assets = build()
    ASSETS.mkdir(parents=True, exist_ok=True)

    if args.check:
        stale = [
            path
            for path, content in assets.items()
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        if stale:
            print("These assets are stale. Run: python tools/render_assets.py", file=sys.stderr)
            for path in sorted(stale):
                print(f"  {path.relative_to(ROOT).as_posix()}", file=sys.stderr)
            return 1
        print(f"{len(assets)} assets are current.")
        return 0

    for path, content in sorted(assets.items()):
        path.write_text(content, encoding="utf-8", newline="\n")
    print(f"Wrote {len(assets)} assets to {ASSETS.relative_to(ROOT).as_posix()}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
