"""Regenerate the diagrams and terminal captures used in the documentation.

Every image in `docs/assets/` is produced by this script and by nothing else. Two
consequences follow, and both are the point:

* An asset cannot drift from what it illustrates. `--check` regenerates everything
  into memory and compares it byte for byte with what is committed, so a diagram that
  no longer matches the architecture fails the build the same way a stale test does.
* A terminal capture is real output. Captures are produced by running the command and
  keeping what it printed. Nothing here draws a screenshot of behaviour that does not
  exist yet; a verb that is not built renders as a verb that is not built.

  One consequence is worth naming. A plan produced from facts records the moment it was
  produced, so capturing that would put a clock in a file compared byte for byte. The
  capture below therefore renders a plan that already exists, which is a real command
  with a real answer. That the pipeline still produces the plan correctly is checked by
  rendering the golden plans twice and comparing the bytes, which is a better proof than
  a picture of one run.

Output is deterministic: no timestamps, no random ids, no locale-dependent formatting.
Themes are rendered as separate light and dark files so the documentation can pick one
with `<picture>` rather than shipping an image that is unreadable on half the screens
that open it.

Usage:

    python tools/render_assets.py            # write docs/assets/
    python tools/render_assets.py --check    # fail if the committed assets are stale
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections.abc import Iterable, Sequence
from dataclasses import dataclass, replace
from pathlib import Path

from basewright.cli import EXIT_CODES
from basewright.facts import HostFacts, load_facts
from basewright.preflight import evaluate
from basewright.profiles import load_profile
from basewright.profiles.model import Profile
from basewright.request import resolve_request

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "docs" / "assets"

MONO = "ui-monospace, SFMono-Regular, Menlo, Consolas, 'Liberation Mono', monospace"
SANS = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif"

#: Monospace advance width as a fraction of the font size. Close enough for every
#: font in the stack above, and only used to size the canvas.
CHAR_WIDTH = 0.6

GENERATED_BY = "<!-- Generated by tools/render_assets.py. Do not edit by hand. -->"


@dataclass(frozen=True)
class Theme:
    """The colours of one rendering. Values follow the palette GitHub renders with."""

    name: str
    bg: str
    panel: str
    fg: str
    muted: str
    line: str
    accent: str
    ok: str
    warn: str
    block: str


THEMES: tuple[Theme, ...] = (
    Theme(
        name="light",
        bg="#ffffff",
        panel="#f6f8fa",
        fg="#1f2328",
        muted="#59636e",
        line="#d1d9e0",
        accent="#0969da",
        ok="#1a7f37",
        warn="#9a6700",
        block="#cf222e",
    ),
    Theme(
        name="dark",
        bg="#0d1117",
        panel="#151b23",
        fg="#e6edf3",
        muted="#9198a1",
        line="#3d444d",
        accent="#4493f8",
        ok="#3fb950",
        warn="#d29922",
        block="#f85149",
    ),
)


# --------------------------------------------------------------------------- svg


def escape(text: str) -> str:
    return (
        text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
    )


def svg(width: int, height: int, body: Iterable[str]) -> str:
    """Wrap rendered elements in a document, with the arrowhead every diagram uses."""
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" role="img">',
        GENERATED_BY,
        "<defs>",
        '<marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" '
        'markerHeight="6" orient="auto">',
        '<path d="M 0 0 L 10 5 L 0 10 z" fill="context-stroke"/>',
        "</marker>",
        "</defs>",
        *body,
        "</svg>",
    ]
    return "\n".join(parts) + "\n"


def rect(
    x: float,
    y: float,
    w: float,
    h: float,
    *,
    fill: str,
    stroke: str = "none",
    radius: float = 6,
    width: float = 1,
    dash: str | None = None,
) -> str:
    dash_attr = f' stroke-dasharray="{dash}"' if dash else ""
    return (
        f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{radius}" fill="{fill}" '
        f'stroke="{stroke}" stroke-width="{width}"{dash_attr}/>'
    )


def text(
    x: float,
    y: float,
    content: str,
    *,
    fill: str,
    size: float = 13,
    family: str = SANS,
    weight: str = "normal",
    anchor: str = "start",
    spacing: str = "normal",
) -> str:
    return (
        f'<text x="{x}" y="{y}" fill="{fill}" font-family="{family}" font-size="{size}" '
        f'font-weight="{weight}" text-anchor="{anchor}" letter-spacing="{spacing}" '
        f'xml:space="preserve">{escape(content)}</text>'
    )


def line(x1: float, y1: float, x2: float, y2: float, *, stroke: str, arrow: bool = False) -> str:
    marker = ' marker-end="url(#arrow)"' if arrow else ""
    return (
        f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{stroke}" '
        f'stroke-width="1.5"{marker}/>'
    )


# ---------------------------------------------------------------- terminal cards

#: Highlighting rules applied to captured output, in order. The first match on a line
#: wins. These describe the report vocabulary, not any one engine.
HIGHLIGHTS: tuple[tuple[re.Pattern[str], str], ...] = (
    (re.compile(r"^\s*\$ "), "accent"),
    (re.compile(r"\bBLOCK\b|\bREFUSED\b|\bFAIL(ED)?\b"), "block"),
    (re.compile(r"\bWARN(ING)?\b|^\s*~ "), "warn"),
    (re.compile(r"\bPASS\b|\bOK\b|^\s*\+ "), "ok"),
    (re.compile(r"^[A-Z][A-Z ]{2,}$"), "accent"),
    (re.compile(r"^\s*#"), "muted"),
)


def _colour_for(line_text: str, theme: Theme) -> str:
    for pattern, attribute in HIGHLIGHTS:
        if pattern.search(line_text):
            return str(getattr(theme, attribute))
    return theme.fg


def render_terminal(title: str, lines: Sequence[str], theme: Theme) -> str:
    """Draw captured console output as a terminal window."""
    size = 12.5
    leading = 18
    pad = 18
    chrome = 34

    columns = max((len(line_text) for line_text in lines), default=0)
    width = int(pad * 2 + max(columns, len(title) + 12) * size * CHAR_WIDTH) + 8
    height = int(chrome + pad + max(len(lines), 1) * leading + pad)

    body: list[str] = [
        rect(0, 0, width, height, fill=theme.panel, stroke=theme.line, radius=8),
        rect(0, 0, width, chrome, fill=theme.bg, stroke="none", radius=8),
        f'<rect x="0" y="{chrome - 8}" width="{width}" height="8" fill="{theme.bg}"/>',
        line(0, chrome, width, chrome, stroke=theme.line),
    ]
    for index, colour in enumerate((theme.block, theme.warn, theme.ok)):
        body.append(f'<circle cx="{18 + index * 16}" cy="{chrome / 2}" r="5" fill="{colour}"/>')
    body.append(
        text(
            width / 2,
            chrome / 2 + 4,
            title,
            fill=theme.muted,
            size=12,
            family=SANS,
            anchor="middle",
        )
    )

    baseline = chrome + pad + leading - 5
    for index, line_text in enumerate(lines):
        body.append(
            text(
                pad,
                baseline + index * leading,
                line_text,
                fill=_colour_for(line_text, theme),
                size=size,
                family=MONO,
            )
        )
    return svg(width, height, body)


# --------------------------------------------------------------------- diagrams


def render_pipeline(theme: Theme) -> str:
    """The five verbs, and the fact that only one of them writes to the host."""
    steps = (
        ("gather", "facts"),
        ("preflight", "gates"),
        ("plan", "artifact"),
        ("apply", "change"),
        ("verify", "proof"),
    )
    box_w, box_h, gap, left, top = 158.0, 60.0, 34.0, 24.0, 46.0
    width = int(left * 2 + len(steps) * box_w + (len(steps) - 1) * gap)
    height = 196

    body: list[str] = [
        rect(0, 0, width, height, fill=theme.bg),
        text(
            left, 28, "The five verbs, always in this order", fill=theme.fg, size=14, weight="600"
        ),
    ]

    for index, (verb, subtitle) in enumerate(steps):
        x = left + index * (box_w + gap)
        writes = verb == "apply"
        border = theme.warn if writes else theme.line
        body.extend(
            (
                rect(
                    x,
                    top,
                    box_w,
                    box_h,
                    fill=theme.panel,
                    stroke=border,
                    width=2 if writes else 1,
                ),
                text(
                    x + box_w / 2,
                    top + 26,
                    verb,
                    fill=theme.fg,
                    size=16,
                    family=MONO,
                    weight="600",
                    anchor="middle",
                ),
                text(
                    x + box_w / 2,
                    top + 46,
                    subtitle,
                    fill=theme.muted,
                    size=12,
                    anchor="middle",
                ),
                text(
                    x + box_w / 2,
                    top + box_h + 26,
                    "changes the target" if writes else "reads only",
                    fill=theme.warn if writes else theme.muted,
                    size=11.5,
                    anchor="middle",
                ),
            )
        )
        if index < len(steps) - 1:
            body.append(
                line(
                    x + box_w + 8,
                    top + box_h / 2,
                    x + box_w + gap - 8,
                    top + box_h / 2,
                    stroke=theme.muted,
                    arrow=True,
                )
            )

    body.append(
        text(
            left,
            height - 22,
            "A block produces no plan, only a refusal. Warnings must be acknowledged before "
            "apply will run.",
            fill=theme.muted,
            size=12.5,
        )
    )
    return svg(width, height, body)


def render_decides_acts(theme: Theme) -> str:
    """Where the decisions are made, and where they are carried out."""
    width, height = 980, 300
    panel_w, panel_h, top = 290.0, 176.0, 62.0
    left_x, right_x = 24.0, 666.0
    middle_x, middle_w = 380.0, 220.0

    decisions = (
        "normalize host facts",
        "evaluate the gate rules",
        "size parameters from rules",
        "resolve the layout",
        "assemble and render the plan",
    )
    actions = (
        "add the vendor repository",
        "install the packages",
        "create accounts and paths",
        "write the configuration",
        "enable and start the service",
    )

    def panel(x: float, title: str, subtitle: str, items: Sequence[str], accent: str) -> list[str]:
        parts = [
            rect(x, top, panel_w, panel_h, fill=theme.panel, stroke=theme.line),
            f'<rect x="{x}" y="{top}" width="4" height="{panel_h}" rx="2" fill="{accent}"/>',
            text(x + 20, top + 30, title, fill=theme.fg, size=15, weight="600"),
            text(x + 20, top + 50, subtitle, fill=theme.muted, size=12),
        ]
        for index, item in enumerate(items):
            parts.append(
                text(x + 20, top + 78 + index * 20, f"·  {item}", fill=theme.fg, size=12.5)
            )
        return parts

    body: list[str] = [
        rect(0, 0, width, height, fill=theme.bg),
        text(
            left_x,
            34,
            "Ansible decides nothing. Python decides everything.",
            fill=theme.fg,
            size=15,
            weight="600",
        ),
        *panel(
            left_x, "Python decides", "unit-testable, no host required", decisions, theme.accent
        ),
        *panel(right_x, "Ansible acts", "idempotent, changes the host", actions, theme.warn),
        rect(
            middle_x,
            top + 52,
            middle_w,
            72,
            fill=theme.bg,
            stroke=theme.accent,
            dash="5 4",
        ),
        text(
            middle_x + middle_w / 2,
            top + 80,
            "plan.json",
            fill=theme.accent,
            size=15,
            family=MONO,
            weight="600",
            anchor="middle",
        ),
        text(
            middle_x + middle_w / 2,
            top + 102,
            "the only thing apply reads",
            fill=theme.muted,
            size=11.5,
            anchor="middle",
        ),
        line(
            left_x + panel_w + 12,
            top + 88,
            middle_x - 12,
            top + 88,
            stroke=theme.muted,
            arrow=True,
        ),
        line(
            middle_x + middle_w + 12,
            top + 88,
            right_x - 12,
            top + 88,
            stroke=theme.muted,
            arrow=True,
        ),
        text(
            left_x,
            height - 22,
            "Sizing arithmetic and gate evaluation in a template would be untestable. "
            "They live in Python, and the plan carries the result.",
            fill=theme.muted,
            size=12.5,
        ),
    ]
    return svg(width, height, body)


def render_finished_vs_fit(theme: Theme) -> str:
    """The thesis, as two columns."""
    width, height = 900, 296
    panel_w, panel_h, top = 414.0, 194.0, 58.0
    left_x, right_x = 24.0, 462.0

    finished = (
        "the job exited zero",
        "the package is present",
        "parameters are whatever the package shipped",
        "nobody checked whether the machine fits",
        "no record of a single decision",
    )
    fit = (
        "the host was gated against the requirements",
        "parameters were sized from the real facts",
        "every value carries the rule that produced it",
        "the running instance was verified against the plan",
        "the fortieth server is built like the first",
    )

    def panel(x: float, title: str, items: Sequence[str], accent: str) -> list[str]:
        parts = [
            rect(x, top, panel_w, panel_h, fill=theme.panel, stroke=theme.line),
            f'<rect x="{x}" y="{top}" width="4" height="{panel_h}" rx="2" fill="{accent}"/>',
            text(x + 20, top + 32, title, fill=accent, size=15, weight="600"),
        ]
        for index, item in enumerate(items):
            parts.append(
                text(x + 20, top + 62 + index * 24, f"·  {item}", fill=theme.fg, size=12.5)
            )
        return parts

    body: list[str] = [
        rect(0, 0, width, height, fill=theme.bg),
        text(
            left_x,
            32,
            "An install that finished is not the same thing as an instance fit for production.",
            fill=theme.fg,
            size=15,
            weight="600",
        ),
        *panel(left_x, "An install that finished", finished, theme.block),
        *panel(right_x, "An instance fit for production", fit, theme.ok),
        text(
            left_x,
            height - 20,
            "Basewright refuses to conflate the two: a host that fails preflight is refused "
            "with a reason, never half-installed.",
            fill=theme.muted,
            size=12.5,
        ),
    ]
    return svg(width, height, body)


#: The decision records, grouped by the question each one answers. This is the source
#: of the decision map, and test/unit/test_decision_records.py asserts it matches the
#: files in docs/adr/ exactly -- in both directions -- so the picture cannot describe a
#: set of decisions the repository does not have.
#: The eight files a profile is made of, what each declares, and which step consumes it.
#: A test keeps this list and the schemas in ``schema/`` in step with one another, so the
#: picture cannot quietly describe a profile format that no longer exists.
PROFILE_ANATOMY: tuple[tuple[str, str, str], ...] = (
    ("profile.yml", "identity, OS families, defaults", "every step"),
    ("support-matrix.yml", "version x OS x arch x end of life", "preflight"),
    ("requirements.yml", "gate rules, and the way out of each", "preflight"),
    ("layout.yml", "paths, modes, the service account", "plan, apply"),
    ("sizing.yml", "parameter rules, each with its reason", "plan"),
    ("packages.yml", "repositories, packages, service unit", "apply"),
    ("apply.yml", "config files, host settings, secrets", "plan, apply"),
    ("verify.yml", "assertions about the running instance", "verify"),
)

#: What a host is described by, in the order the model declares it. Kept in step with
#: the model by a test, so the picture cannot describe facts nothing collects.
FACTS_MODEL: tuple[tuple[str, str, str], ...] = (
    ("host", "the machine, as it was addressed", "every report"),
    ("collected_at", "when it was observed, in UTC", "apply, before trusting a plan"),
    ("os", "family, distribution, version, codename", "os.supported, packages"),
    ("arch", "one spelling of the machine", "arch.supported"),
    ("cpu", "cores, threads, model", "cpu.min_cores, sizing"),
    ("memory", "installed, available, swap", "mem.min_total, sizing"),
    ("mounts", "path, filesystem, free space, spindle", "every disk rule, sizing"),
    ("listening_ports", "what already answers, and on what", "port.free"),
    ("services", "what is already installed", "the conflict rule"),
    ("locales", "what the host can be asked for", "locale.present"),
    ("privileges", "the account, and whether it escalates", "host.privilege"),
    ("reachable_repositories", "which package repositories answer", "repo.reachable"),
    ("time_sync", "the clock, and whether it is in step", "time.sync"),
    ("kernel", "swappiness, huge pages, overcommit", "os.thp, os.swappiness"),
    ("firewall", "whether it is on, and what it admits", "firewall.state"),
)

#: The sections a plan carries, and which step reads each one. Kept in step with
#: schema/plan.schema.json by a test: the picture cannot describe a contract that moved,
#: which matters more here than anywhere else, because this one is frozen.
PLAN_ANATOMY: tuple[tuple[str, str, str], ...] = (
    ("schema_version", "the version of this contract", "apply, before anything else"),
    ("plan_id", "a digest of the plan, minus when", "the task log, and whoever approves"),
    ("generated_at", "when it was written, in UTC", "a reader; nothing decides on it"),
    ("tool_version", "which build produced it", "apply, which refuses another major"),
    ("profile", "the engine, and the profile version", "verify, tracing a value to a rule"),
    ("request", "host, version, environment, instance", "every step"),
    ("host", "the machine the decisions were made on", "apply, before trusting the plan"),
    ("preflight", "every rule, and what it made of it", "the reviewer; block is always 0"),
    ("parameters", "each value, with its rule and reason", "apply, verify"),
    ("layout", "paths, modes, owner, and the mount", "apply, verify"),
    ("packages", "repository, package names, service", "apply, verify"),
    ("configuration", "template, destination, mode, owner", "apply"),
    ("tunables", "host settings, and what they are now", "apply"),
    ("changes", "everything apply would do, in order", "the person who approves it"),
    ("secrets", "a name and a place; never a value", "apply, writing them once"),
    ("result", "whether it applies, and what to sign", "apply, which refuses otherwise"),
)


#: One value, from the rule that produced it to the line it occupies in a plan. The
#: numbers are the ones the pipeline really produces for this host and this parameter,
#: and a test holds them against the committed golden plan, so the picture cannot go on
#: illustrating arithmetic the planner has stopped doing.
SIZING_JOURNEY_HOST = "large"
SIZING_JOURNEY_PARAMETER = "cache_size"
#: What the picture says underneath the journey. Held against the golden plan by a test,
#: because a caption naming a number is a claim about the artifact like any other.
SIZING_JOURNEY_FOOTER: tuple[str, ...] = (
    "The order the bounds are applied in is not cosmetic: rounding down after a floor "
    "lands under that floor, so a bound is the last thing applied and it wins.",
    "The plan carries 8589934592 and renders 8.0 GiB. Verify compares the number; the "
    "engine's own spelling of it is the template's business.",
)

SIZING_JOURNEY: tuple[tuple[str, str, str], ...] = (
    (
        "the rule",
        "0.25 * host.memory.total_bytes",
        "sizing.yml, with min 128MiB, max 8GiB, round_to 128MiB",
    ),
    ("the host", "512.0 GiB", "host.memory.total_bytes, as the machine reported it"),
    ("evaluated", "128.0 GiB", "the expression, read by the interpreter, never run"),
    ("rounded", "128.0 GiB", "down to a multiple of 128MiB; already one, so unchanged"),
    ("bounded", "8.0 GiB", "held at the ceiling, which the plan records as bounded_by max"),
    (
        "in the plan",
        "cache_size 8.0 GiB",
        "with exampledb.cache_size beside it, and the reason that rule carries",
    ),
)


DECISIONS: tuple[tuple[str, tuple[tuple[str, str], ...]], ...] = (
    (
        "What it produces",
        (
            ("0001", "plan before apply"),
            ("0009", "rules explain themselves"),
            ("0010", "match, or refuse"),
            ("0016", "canonical values, not rendered"),
            ("0017", "a plan is named by its content"),
        ),
    ),
    (
        "How it is built",
        (
            ("0002", "engines are data"),
            ("0008", "Python decides, Ansible acts"),
            ("0020", "the playbook is the entry point"),
            ("0021", "the collector is told the engine"),
            ("0011", "packages, never source"),
            ("0014", "rules are expressions"),
            ("0015", "shared gates are code"),
            ("0018", "what apply does is declared"),
        ),
    ),
    (
        "What it refuses",
        (
            ("0003", "humans choose the version"),
            ("0004", "two severities, no override"),
            ("0012", "starts at a reachable host"),
            ("0013", "backups belong elsewhere"),
        ),
    ),
    (
        "How it is operated",
        (
            ("0005", "Semaphore is the interface"),
            ("0006", "one technical account"),
            ("0007", "secrets stay out of artifacts"),
            ("0019", "exit codes are the contract"),
        ),
    ),
)


#: Counted in words up to the point where a project has more decisions than a reader can
#: hold in mind at once. Past that the number is the more useful of the two.
_NUMBERS: tuple[str, ...] = (
    "Zero",
    "One",
    "Two",
    "Three",
    "Four",
    "Five",
    "Six",
    "Seven",
    "Eight",
    "Nine",
    "Ten",
    "Eleven",
    "Twelve",
    "Thirteen",
    "Fourteen",
    "Fifteen",
    "Sixteen",
    "Seventeen",
    "Eighteen",
    "Nineteen",
    "Twenty",
)


def _counted(total: int) -> str:
    """How many, in the words a sentence would use. Derived, so it cannot go stale."""
    return _NUMBERS[total] if total < len(_NUMBERS) else str(total)


def render_decisions(theme: Theme) -> str:
    """The decision records, grouped by the question each one answers."""
    width = 980
    left, top, gap = 18.0, 52.0, 16.0
    column_w = (width - left * 2 - gap * (len(DECISIONS) - 1)) / len(DECISIONS)
    rows = max(len(entries) for _, entries in DECISIONS)
    panel_h = 46.0 + rows * 40.0 + 8.0
    height = int(top + panel_h + 46)

    body: list[str] = [
        rect(0, 0, width, height, fill=theme.bg),
        text(
            left,
            30,
            f"{_counted(sum(len(entries) for _, entries in DECISIONS))} decisions, and the "
            "question each one answers",
            fill=theme.fg,
            size=15,
            weight="600",
        ),
    ]

    for index, (heading, entries) in enumerate(DECISIONS):
        x = left + index * (column_w + gap)
        body.extend(
            (
                rect(x, top, column_w, panel_h, fill=theme.panel, stroke=theme.line),
                text(x + 16, top + 27, heading, fill=theme.accent, size=13, weight="600"),
                line(x + 16, top + 38, x + column_w - 16, top + 38, stroke=theme.line),
            )
        )
        for row, (number, title) in enumerate(entries):
            y = top + 60 + row * 40
            body.extend(
                (
                    text(x + 16, y, number, fill=theme.muted, size=11.5, family=MONO),
                    text(x + 16, y + 17, title, fill=theme.fg, size=12.5),
                )
            )

    body.append(
        text(
            left,
            height - 18,
            "Each record states the context, the decision, its consequences and the "
            "alternatives that were rejected.",
            fill=theme.muted,
            size=12.5,
        )
    )
    return svg(width, height, body)


def render_table(
    theme: Theme,
    *,
    title: str,
    subtitle: str,
    headings: tuple[str, str, str],
    rows: Sequence[tuple[str, str, str]],
    footer: Sequence[str],
    columns: tuple[float, float, float] = (20, 210, 560),
    width: int = 900,
) -> str:
    """Draw a three-column table: a name, what it carries, and what reads it.

    Two diagrams answer the same question about different things -- what a profile is made
    of, and what a host is described by -- so they are drawn by the same code. A second
    copy of this would drift in spacing first and in substance later.
    """
    left, top, row_h = 24.0, 84.0, 34.0
    name_x, middle_x, reader_x = (left + offset for offset in columns)
    panel_w = width - left * 2
    panel_h = 34.0 + len(rows) * row_h + 12.0
    height = int(top + panel_h + 34 + len(footer) * 20)

    body: list[str] = [
        rect(0, 0, width, height, fill=theme.bg),
        text(left, 34, title, fill=theme.fg, size=15, weight="600"),
        text(left, 56, subtitle, fill=theme.muted, size=12.5),
        rect(left, top, panel_w, panel_h, fill=theme.panel, stroke=theme.line),
        text(name_x, top + 22, headings[0], fill=theme.muted, size=11, spacing="0.08em"),
        text(middle_x, top + 22, headings[1], fill=theme.muted, size=11, spacing="0.08em"),
        text(reader_x, top + 22, headings[2], fill=theme.muted, size=11, spacing="0.08em"),
        line(left + 12, top + 32, left + panel_w - 12, top + 32, stroke=theme.line),
    ]

    for index, (name, middle, reader) in enumerate(rows):
        baseline = top + 34 + row_h * index + 22
        body.append(text(name_x, baseline, name, fill=theme.accent, size=12.5, family=MONO))
        body.append(text(middle_x, baseline, middle, fill=theme.fg, size=12.5))
        body.append(text(reader_x, baseline, reader, fill=theme.muted, size=12.5))

    for index, note in enumerate(footer):
        body.append(
            text(
                left,
                top + panel_h + 26 + index * 20,
                note,
                fill=theme.muted,
                size=12.5,
            )
        )
    return svg(width, height, body)


def render_profile_anatomy(theme: Theme) -> str:
    """The eight files an engine is made of, and which step reads each one."""
    return render_table(
        theme,
        title="An engine, as data: eight files and the step that reads each one",
        subtitle="Adding an engine means adding this directory. It never means editing the core.",
        headings=("FILE", "DECLARES", "READ BY"),
        rows=PROFILE_ANATOMY,
        footer=(
            "Every file is closed by a JSON Schema: an unknown key is an error, so a profile "
            "cannot imply behaviour the core does not have.",
            "A ninth schema covers plan.json, the artifact these eight produce and the only "
            "thing apply reads.",
        ),
    )


#: How a verb runs, once there is a machine at the end of it. Each step names what does the
#: work, because the whole arrangement is an answer to the question of which half is in
#: charge -- and the answer is not the one most tools give (ADR-0020).
VERB_PIPELINE: tuple[tuple[str, str, str], ...] = (
    ("Semaphore", "runs the playbook, holds the key", "the operator's interface"),
    ("playbook", "reaches the host and reads it", "ansible/playbooks/gather.yml"),
    ("host", "answers; nothing about it changes", "the machine, over SSH"),
    ("facts.json", "what it said, in the frozen contract", "written on the control node"),
    ("basewright", "reads the document back, and reports", "no network, no host, no SSH"),
)


#: The one fact in the contract with three answers, and the case each of them is. Two of
#: the rows are not about the fact at all: they are the two ways the rule decides it has
#: nothing to decide, and they are here because "skip" appearing in a report means one of
#: four different things and a reader is entitled to know which.
#:
#: The verdict column is not written here. It is produced by running the rule, below, so
#: the picture cannot claim an outcome the gate does not reach.
#: A repository that is not the one this profile declares. Any url will do; what the row
#: it appears in is about is that it is not the same string.
ELSEWHERE = "https://packages.elsewhere.invalid/apt"

REACHABILITY: tuple[tuple[str, str, tuple[str, ...] | None], ...] = (
    ("(no key)", "nobody named an engine, so the host was never asked", None),
    ("[]", "the host was asked, and reached nothing at all", ()),
    ('["the url"]', "the host reached the repository the profile names", ("url",)),
    ('["another url"]', "the host reached something, but not that", ("other",)),
    ("(no repository)", "the profile installs from what the host already has", ()),
)


def _reachability_rows() -> tuple[tuple[str, str, str], ...]:
    """Run `repo.reachable` against each case, and report what it actually answered."""
    profile = load_profile(ROOT / "test" / "fixtures" / "profiles" / "exampledb")
    facts = load_facts(ROOT / "test" / "fixtures" / "hosts" / "typical.json")
    packages = profile.packages_for(facts.os.family)
    assert packages is not None and packages.repository is not None
    declared = packages.repository.url
    stripped = {name: replace(entry, repository=None) for name, entry in profile.packages.items()}
    without = replace(profile, packages=stripped)

    rows: list[tuple[str, str, str]] = []
    for collected, meaning, reachable in REACHABILITY:
        engine = without if collected == "(no repository)" else profile
        urls = (
            None
            if reachable is None
            else tuple(declared if name == "url" else ELSEWHERE for name in reachable)
        )
        outcome = _verdict(replace(facts, reachable_repositories=urls), engine)
        rows.append((collected, meaning, outcome))
    return tuple(rows)


def _verdict(facts: HostFacts, profile: Profile) -> str:
    """What the gate engine says about `repo.reachable` for one host."""
    request = resolve_request(profile, host="a-host.invalid", environment="production")
    result = evaluate(facts, profile, request)
    entry = next(item for item in result.results if item.identifier == "repo.reachable")
    return entry.outcome.value.upper()


def render_reachability(theme: Theme) -> str:
    """The three answers one fact gives, and the verdict each of them produces."""
    return render_table(
        theme,
        title="reachable_repositories: the one fact in the contract with three answers",
        subtitle=(
            "Absent is not empty. Nobody having asked and the host having reached nothing "
            "are different answers, and the rule tells them apart."
        ),
        headings=("WHAT WAS COLLECTED", "WHAT IT MEANS", "VERDICT"),
        rows=_reachability_rows(),
        footer=(
            "Which repositories to try comes from the profile, so this is the one fact "
            "whose collection depends on knowing what is being provisioned (ADR-0021).",
            "Urls are compared exactly, never approximately: two spellings of one "
            "repository are two different claims about what was proved.",
        ),
        columns=(20, 200, 700),
    )


def render_verb_pipeline(theme: Theme) -> str:
    """Which half of the tool is in charge, and where the two of them meet."""
    return render_table(
        theme,
        title="How a verb runs: the playbook is the entry point, not the CLI",
        subtitle=(
            "The deciding half never reaches a machine. That is what keeps it a pure "
            "function of a document, and testable without one."
        ),
        headings=("STEP", "WHAT IT DOES", "WHAT IT IS"),
        rows=VERB_PIPELINE,
        footer=(
            "The document a playbook writes and the fixtures committed under test/ are the "
            "same kind of thing, read by the same code.",
            "So a fixture is not a simulation of a collected host. It is a collected host "
            "with the collection done earlier.",
        ),
        columns=(20, 130, 460),
        width=940,
    )


def render_exit_codes(theme: Theme) -> str:
    """The exit codes, drawn from the registry the CLI actually returns.

    This one is a contract with a second system rather than a description of this one, so
    the picture is worth having: a template author reads it once and never has to read the
    source. Rendered from ``EXIT_CODES`` so it cannot describe a set the tool does not have.
    """
    return render_table(
        theme,
        title="The four exit codes, and what a red task in Semaphore means",
        subtitle=(
            "Semaphore marks a task red on any non-zero code. What the number carries is "
            "what to do next, not that something failed."
        ),
        headings=("CODE", "WHAT HAPPENED", "WHAT TO DO"),
        rows=tuple((str(entry.code), entry.meaning, entry.response) for entry in EXIT_CODES),
        footer=(
            "The line between the two non-zero answers: a file that could not be read at "
            "all is 64, a file that was read and is not acceptable is 2.",
            "69 is temporary. It leaves when the verb it names is built, which narrows the "
            "set rather than changing it.",
        ),
        columns=(20, 100, 420),
        width=940,
    )


def render_plan_anatomy(theme: Theme) -> str:
    """What a plan carries, and which step reads each part of it."""
    return render_table(
        theme,
        title="The plan, section by section: what each carries and what reads it",
        subtitle=(
            "Apply consumes this and nothing else. A value apply needs that is not here "
            "means the plan is incomplete, not that apply should go and look."
        ),
        headings=("SECTION", "CARRIES", "READ BY"),
        rows=PLAN_ANATOMY,
        footer=(
            "The contract is closed and frozen. An unknown key is an error, and a change to "
            "any field here is a version of the contract rather than a patch.",
            "The id is a digest of everything above except generated_at, so two runs that "
            "decided the same thing produce the same name for it.",
        ),
        columns=(20, 190, 540),
    )


def render_sizing_journey(theme: Theme) -> str:
    """One value, from the rule that produced it to the line it occupies in a plan."""
    width = 940
    left, top, row_h = 24.0, 96.0, 52.0
    panel_w = width - left * 2
    panel_h = 16.0 + len(SIZING_JOURNEY) * row_h
    footer = SIZING_JOURNEY_FOOTER
    height = int(top + panel_h + 34 + len(footer) * 20)

    body: list[str] = [
        rect(0, 0, width, height, fill=theme.bg),
        text(
            left,
            34,
            "How one value is arrived at, and what it takes with it",
            fill=theme.fg,
            size=15,
            weight="600",
        ),
        text(
            left,
            56,
            f"{SIZING_JOURNEY_PARAMETER} on db-{SIZING_JOURNEY_HOST}.invalid: a machine with "
            "more memory than the rule will let the parameter have.",
            fill=theme.muted,
            size=12.5,
        ),
        text(
            left,
            76,
            "Every step is Python. None of it is a template, and none of it is evaluated "
            "on the host.",
            fill=theme.muted,
            size=12.5,
        ),
        rect(left, top, panel_w, panel_h, fill=theme.panel, stroke=theme.line),
    ]

    stage_x = left + 20
    value_x = left + 132
    note_x = left + 372

    for index, (stage, value, note) in enumerate(SIZING_JOURNEY):
        baseline = top + 16 + row_h * index + 22
        last = index == len(SIZING_JOURNEY) - 1
        body.extend(
            (
                text(stage_x, baseline, stage, fill=theme.muted, size=11.5, spacing="0.06em"),
                text(
                    value_x,
                    baseline,
                    value,
                    fill=theme.accent if last else theme.fg,
                    size=13,
                    family=MONO,
                    weight="600" if last else "normal",
                ),
                text(note_x, baseline, note, fill=theme.muted, size=12),
            )
        )
        if not last:
            body.append(
                line(
                    stage_x + 44,
                    baseline + 10,
                    stage_x + 44,
                    baseline + row_h - 14,
                    stroke=theme.line,
                    arrow=True,
                )
            )

    for index, note in enumerate(footer):
        body.append(text(left, top + panel_h + 26 + index * 20, note, fill=theme.muted, size=12.5))
    return svg(width, height, body)


def render_facts_model(theme: Theme) -> str:
    """What a host is described by, and which rule reads each part of it."""
    return render_table(
        theme,
        title="A host, as the rules see it: every fact, and what consults it",
        subtitle=(
            "The model is not everything a machine could be asked. It is what the rules need "
            "to reach a verdict."
        ),
        headings=("FACT", "CARRIES", "READ BY"),
        rows=FACTS_MODEL,
        footer=(
            "A fact nothing consults is a fact that rots quietly, because nothing fails when "
            "it stops being collected correctly.",
            "Facts a blocking rule needs are required; the ones only a warning reads may be "
            "absent, and that warning is skipped rather than guessed.",
        ),
        columns=(20, 190, 540),
    )


# ------------------------------------------------------------------- collection


@dataclass(frozen=True)
class Capture:
    """One terminal image: what to run, and what the picture is called.

    Declared rather than run inline so that the command is inspectable. The README shows
    each of these as a copy-pasteable line above the picture it produced, and a test holds
    the two together -- so what a reader copies is provably what made the image below it.
    """

    #: The stem of the files written under docs/assets/.
    name: str
    #: The caption drawn on the window.
    title: str
    #: The arguments after ``python -m``.
    command: tuple[str, ...]
    #: The prompt line to draw, when running it here is not what a reader would type. It
    #: changes what the picture says to type; it never changes what was run, and what was
    #: run is what the picture shows.
    display: str | None = None

    @property
    def prompt(self) -> str:
        """The command line the picture shows, and the one a reader copies."""
        if self.display is not None:
            return self.display
        if self.command[0] == "basewright.cli":
            return " ".join(("basewright", *self.command[1:]))
        return " ".join(self.command)


#: Every terminal image in the documentation. Each is produced by running the command and
#: keeping what it printed, so none of them can show a verb working before it works.
CAPTURES: tuple[Capture, ...] = (
    Capture("cli-help", "basewright --help", ("basewright.cli", "--help")),
    Capture(
        "plan-rendered",
        "the plan, as the person approving it reads it",
        ("basewright.cli", "plan", "--from", "test/golden/postgresql/plan/typical.json"),
    ),
    Capture(
        "plan-edited",
        "a plan whose name no longer matches what it says",
        ("basewright.cli", "plan", "--from", "test/fixtures/plan/edited.json"),
    ),
    Capture(
        "cli-gather",
        "basewright gather",
        ("basewright.cli", "gather", "--facts", "test/fixtures/hosts/typical.json"),
    ),
    Capture(
        "engine-unknown",
        "an engine nothing has a profile for",
        (
            "basewright.cli",
            "preflight",
            "--facts",
            "test/fixtures/hosts/typical.json",
            "--engine",
            "mysql",
        ),
    ),
    Capture(
        "preflight-refused",
        "a host that cannot be provisioned",
        (
            "basewright.cli",
            "preflight",
            "--facts",
            "test/fixtures/hosts/crowded.json",
            "--engine",
            "postgresql",
        ),
    ),
    Capture(
        "preflight-passed",
        "a host that can, with warnings to acknowledge",
        (
            "basewright.cli",
            "preflight",
            "--facts",
            "test/fixtures/hosts/typical.json",
            "--engine",
            "postgresql",
        ),
    ),
    Capture(
        "cli-collected",
        "a host the playbook actually went and read",
        ("basewright.cli", "gather", "--facts", "test/fixtures/hosts/collected.json"),
    ),
    Capture(
        "preflight-unreachable",
        "a host that cannot reach the repository its packages come from",
        (
            "basewright.cli",
            "preflight",
            "--facts",
            "test/fixtures/hosts/asked.json",
            "--profile",
            "test/fixtures/profiles/exampledb",
        ),
    ),
    Capture("cli-verify", "a verb that is not built, saying so", ("basewright.cli", "verify")),
    Capture(
        "profile-refused",
        "a profile that does not hold up",
        ("basewright.profiles", "test/fixtures/profiles/malformed"),
        display="python -m basewright.profiles test/fixtures/profiles/malformed",
    ),
)


def run(entry: Capture) -> list[str]:
    """Run a capture's command and keep what it printed, prompt line included."""
    result = subprocess.run(
        [sys.executable, "-m", *entry.command],
        capture_output=True,
        text=True,
        cwd=ROOT,
        check=False,
    )
    printed = (result.stdout + result.stderr).replace("\r\n", "\n").rstrip("\n")
    lines = [f"$ {entry.prompt}"]
    lines.extend(printed.split("\n") if printed else [])
    return [line_text.rstrip() for line_text in lines]


def build() -> dict[Path, str]:
    """Render every asset. Keys are paths relative to the repository root."""
    assets: dict[Path, str] = {}
    printed = {entry.name: run(entry) for entry in CAPTURES}

    for theme in THEMES:
        suffix = theme.name
        assets[ASSETS / f"pipeline-{suffix}.svg"] = render_pipeline(theme)
        assets[ASSETS / f"decides-acts-{suffix}.svg"] = render_decides_acts(theme)
        assets[ASSETS / f"finished-vs-fit-{suffix}.svg"] = render_finished_vs_fit(theme)
        assets[ASSETS / f"decisions-{suffix}.svg"] = render_decisions(theme)
        assets[ASSETS / f"profile-anatomy-{suffix}.svg"] = render_profile_anatomy(theme)
        assets[ASSETS / f"facts-model-{suffix}.svg"] = render_facts_model(theme)
        assets[ASSETS / f"plan-anatomy-{suffix}.svg"] = render_plan_anatomy(theme)
        assets[ASSETS / f"sizing-journey-{suffix}.svg"] = render_sizing_journey(theme)
        assets[ASSETS / f"exit-codes-{suffix}.svg"] = render_exit_codes(theme)
        assets[ASSETS / f"verb-pipeline-{suffix}.svg"] = render_verb_pipeline(theme)
        assets[ASSETS / f"reachability-{suffix}.svg"] = render_reachability(theme)
        for entry in CAPTURES:
            assets[ASSETS / f"{entry.name}-{suffix}.svg"] = render_terminal(
                entry.title, printed[entry.name], theme
            )

    return assets


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="render_assets",
        description="Regenerate the documentation diagrams and terminal captures.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; fail if what is committed differs from what would be produced.",
    )
    args = parser.parse_args(argv)

    assets = build()
    ASSETS.mkdir(parents=True, exist_ok=True)

    if args.check:
        stale = [
            path
            for path, content in assets.items()
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        # An image nothing renders any more is worse than a stale one: it stays committed,
        # keeps being referenced, and agrees with whatever the documentation says about it
        # for ever. The golden check has caught these from the start; this one did not,
        # until a capture was renamed and its old pair sat in the directory unnoticed.
        orphans = [path for path in sorted(ASSETS.glob("*.svg")) if path not in assets]

        for path in sorted(stale):
            print(f"stale: {path.relative_to(ROOT).as_posix()}", file=sys.stderr)
        for path in orphans:
            name = path.relative_to(ROOT).as_posix()
            print(f"not produced by any renderer: {name}", file=sys.stderr)
        if stale or orphans:
            print(
                "\nRun: python tools/render_assets.py, and delete what it no longer writes.",
                file=sys.stderr,
            )
            return 1
        print(f"{len(assets)} assets are current.")
        return 0

    for path, content in sorted(assets.items()):
        path.write_text(content, encoding="utf-8", newline="\n")
    print(f"Wrote {len(assets)} assets to {ASSETS.relative_to(ROOT).as_posix()}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
